# Starter pipeline
- task: FortifyOnDemandStatic@6
  inputs:
    FortifyProjects: 'https://github.com/ukruthi/AzureTest'
    ReleaseId: 217991
    EntitlementPreference: '2'
    InProgressScanActionType: '0'
    RemediationScanPreference: '0'
    PolicyFailAction: '0'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: FortifyOnDemandStatic@5
  inputs:
    FortifyProjects:'https://github.com/jerryhoff/WebGoat.NET.git'
    BSIToken: 'eyJ0ZW5hbnRJZCI6ODUsInRlbmFudENvZGUiOiJlcXVpZmF4IiwicmVsZWFzZUlkIjoyMjcyMTgsInBheWxvYWRUeXBlIjoiQU5BTFlTSVNfUEFZTE9BRCIsImFzc2Vzc21lbnRUeXBlSWQiOjI4MywidGVjaG5vbG9neVR5cGUiOiJKQVZBL0oyRUUiLCJ0ZWNobm9sb2d5VHlwZUlkIjo3LCJ0ZWNobm9sb2d5VmVyc2lvbiI6IjEuOCIsInRlY2hub2xvZ3lWZXJzaW9uSWQiOjEyLCJhdWRpdFByZWZlcmVuY2UiOiJNYW51YWwiLCJhdWRpdFByZWZlcmVuY2VJZCI6MSwiaW5jbHVkZVRoaXJkUGFydHkiOmZhbHNlLCJpbmNsdWRlT3BlblNvdXJjZUFuYWx5c2lzIjp0cnVlLCJwb3J0YWxVcmkiOiJodHRwczovL2Ftcy5mb3J0aWZ5LmNvbSIsImFwaVVyaSI6Imh0dHBzOi8vYXBpLmFtcy5mb3J0aWZ5LmNvbSIsInNjYW5QcmVmZXJlbmNlIjoiU3RhbmRhcmQiLCJzY2FuUHJlZmVyZW5jZUlkIjoxfQ=='
    APIAuthenticationType: '1'
    APIKey: 'bdfc0fab-b317-4e06-980d-3ead5c762180'
    APISecret: 'J2psQUV3SGdZSnpHRE1TVTZTTDMtV0VhPDZCMTd50'
    EntitlementPreference: '1'
    PurchaseEntitlements: false
    RemediationScanPreference: '1'
    InProgressScanActionType: '1'
    PolicyFailAction: '0'